defaults:
  - app
  - temporal
  - database
  - logging
  - api
  - _self_

# Global settings
app_name: "temporal-workflow-service"
version: "1.0.0"
environment: ${oc.env:ENVIRONMENT,development}

# Hydra settings
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}
  job:
    name: ${app_name}
    chdir: true
