database:
  # Primary database
  primary:
    url: "postgresql://user:password@localhost:5432/temporal_db"
    pool_size: 10
    max_overflow: 20
    pool_timeout: 30
    pool_recycle: 3600
  
  # Redis for caching
  redis:
    url: "redis://localhost:6379/0"
    max_connections: 10
    socket_timeout: 5
    socket_connect_timeout: 5
    retry_on_timeout: true
  
  # Connection settings
  connection:
    echo: false
    echo_pool: false
    pool_pre_ping: true
    pool_recycle: 3600
