logging:
  version: 1
  disable_existing_loggers: false
  
  formatters:
    standard:
      format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
    
    detailed:
      format: "%(asctime)s [%(levelname)s] %(name)s:%(funcName)s:%(lineno)d - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
    
    json:
      format: json
      class: pythonjsonlogger.jsonlogger.JsonFormatter
  
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: standard
      stream: ext://sys.stdout
    
    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: logs/app.log
      maxBytes: 10485760  # 10MB
      backupCount: 5
    
    error_file:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: detailed
      filename: logs/error.log
      maxBytes: 10485760  # 10MB
      backupCount: 5
  
  loggers:
    temporal:
      level: INFO
      handlers: [console, file]
      propagate: false
    
    fastapi:
      level: INFO
      handlers: [console, file]
      propagate: false
    
    sqlalchemy:
      level: WARNING
      handlers: [console, file]
      propagate: false
  
  root:
    level: INFO
    handlers: [console, file, error_file]
