version: '3.8'

services:
  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
      - "8080:8080"
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml

  postgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=temporal
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://temporal:temporal@postgresql:5432/temporal
      - REDIS_URL=redis://redis:6379/0
      - TEMPORAL_HOST=temporal:7233
    volumes:
      - ../src:/app/src
      - ../conf:/app/conf
    depends_on:
      - temporal
      - postgresql
      - redis
    command: ["python", "-m", "src.main", "--config-name=config", "environment=development"]

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://temporal:temporal@postgresql:5432/temporal
      - REDIS_URL=redis://redis:6379/0
      - TEMPORAL_HOST=temporal:7233
    volumes:
      - ../src:/app/src
      - ../conf:/app/conf
    depends_on:
      - temporal
      - postgresql
      - redis
    command: ["python", "scripts/run_worker.py", "--config-name=config", "environment=development"]

volumes:
  postgresql_data:
  redis_data:
